[shell]
program = "powershell"
args = ["-NoExit", "Set-Location $env:USERPROFILE"]


[window]
padding = { x = 3, y = 3 }
dynamic_padding = true
opacity = 0.9
dimensions = { columns = 110, lines = 25 }

[font]
normal = { family = "JetBrainsMono NF", style = "Regular" }
